/**
 * Import third-party libraries
 */

import { AnyAction, Reducer } from 'redux';

/**
 * Interfaces
 */

import { ReducerAction } from '../interfaces/store.interface';

/**
 * Base reducer class
 */

export abstract class AbstractReducer {

    /**
     * Hold map of all dispatch action that generated by decorator
     *
     * @example
     * ```typescript
     * class Reducer extends AbstractReducer {
     *
     *     // optional static var to allow to add type's for auto-complete
     *     // ReducerAction< payload interface / state >
     *     static override actions: {
     *         addBug: ReducerAction<addBugPayload>,
     *         deleteBug: ReducerAction
     *     };
     * }
     * ```
     */

    static actions: {
        [key: string]: ReducerAction<any>
    } = {};

    /**
     * Wrap class with reducer function.
     * This utility method takes a class and converts it to a reducer function
     * allow easy usability
     *
     * @example
     * ```typescript
     * class Reducer extends AbstractReducer {
     *
     *     // optional static var to allow to add type's for auto-complete
     *     // ReducerAction< payload interface / state >
     *     static override actions: {
     *         addBug: ReducerAction<addBugPayload>,
     *         deleteBug: ReducerAction
     *     };
     *
     *     @Action
     *     deleteBug(state: Auth, action: AnyAction) {
     *         return { active_bug: !state.active_bug };
     *     }
     * }
     *
     * export const authReducer = Reducer.createReducer(BUG_INITIAL_STATE);
     * ```
     * @param initialState - the initial state.
     * @return Reducer<State>
     */

    static createReducer<State = any>(this: new () => any, initialState: any): Reducer<State> {
        const instance = new this();
        const namespace = instance.constructor.name + '/';

        return (lastState: State = initialState, action: AnyAction): State => {
            const actionName = action.type.replace(namespace, '');
            const fn = instance[actionName];

            if (fn) {
                return fn.apply(instance, [ lastState, action['payload'] ]);
            }

            return lastState;
        };
    }
}
